# Generated by Django 3.1.5 on 2021-01-13 16:11

from django.db import migrations, models
import django.db.models.deletion
import places.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('origin', places.fields.PlacesField(blank=True, max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(blank=True, default=0.0, help_text='Enter hotel rating')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'ordering': ('-date_time',),
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=999)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='Choose your date to book')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hotels.booking', verbose_name='hotel')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
