# Generated by Django 3.1.5 on 2021-01-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20210113_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-date_time',), 'verbose_name': 'Hotel'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Booking'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hotels.booking', verbose_name='hotel location'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='title',
            field=models.CharField(default='_', max_length=255),
        ),
    ]
